export { HeroSection } from './Hero/HeroSection';
export { TrustEcosystemSection } from './TrustEcosystem/TrustEcosystemSection';
export { ManifestoSection } from './Manifesto/ManifestoSection';
export { SelectedWorkSection } from './SelectedWork/SelectedWorkSection';
export { PhilosophySection } from './Philosophy/PhilosophySection';
export { ServicesSection } from './Services/ServicesSection';
export { TechRadarSection } from './TechRadar/TechRadarSection';
export { BusinessProblemsSection } from './BusinessProblems/BusinessProblemsSection';
export { ProcessSection } from './Process/ProcessSection';
export { CapabilitiesSection } from './Capabilities/CapabilitiesSection';
export { TestimonialsSection } from './Testimonials/TestimonialsSection';
export { ProcurementFAQSection } from './ProcurementFAQ/ProcurementFAQSection';
export { InsightsPreviewSection } from './InsightsPreview/InsightsPreviewSection';
export { ContactSection } from './Contact/ContactSection';

export * from './CapabilitiesMap/CapabilitiesMapSection';
export * from './Industries/IndustriesSection';
export * from './Metrics/MetricsSection';
export * from './Integrations/IntegrationsSection';
export * from './LogoCloud/LogoCloudSection';
export * from './WhyTekmora/WhyTekmoraSection';
export * from './EngagementModels/EngagementModelsSection';
